require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'gemfiles/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/FilePath:
  CustomTransform:
    CarrierWave: carrierwave
  Exclude:
    - 'spec/carrierwave/colore_spec.rb'

Style/Documentation:
  Enabled: false
